/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rwgdfveokzemavstpvyv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3Z2RmdmVva3plbWF2c3Rwdnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzA3MTksImV4cCI6MjA3ODA0NjcxOX0.JaZjZkWEzkp5k-eiuPX-_MQ-mTXAALSNoxv2WjHZdRk"